# Generated by Django 3.0.4 on 2020-03-27 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('reviewContent', models.TextField()),
                ('courseName', models.CharField(max_length=120)),
                ('courseID', models.IntegerField()),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('isAnonymous', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateAdded'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportReason', models.TextField()),
                ('dateReported', models.DateTimeField(auto_now_add=True)),
                ('reporter', models.TextField(default='')),
                ('reviewReported', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='review.Review')),
            ],
            options={
                'ordering': ['dateReported'],
            },
        ),
        migrations.CreateModel(
            name='RecentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('actionDetail', models.TextField()),
                ('actionLink', models.TextField(blank=True, null=True)),
                ('actionType', models.CharField(choices=[('a', 'Alert'), ('i', 'info')], default='i', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recentActions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-dateAdded'],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='review.Review')),
                ('users', models.ManyToManyField(related_name='reviewLikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Dislike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('review', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dislikes', to='review.Review')),
                ('users', models.ManyToManyField(related_name='reviewDislikes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
