# Generated by Django 3.0.4 on 2020-03-23 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20200322_1948'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportReason', models.TextField()),
                ('dateReported', models.DateTimeField(auto_now_add=True)),
                ('reviewReported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='review.Review')),
            ],
            options={
                'ordering': ['dateReported'],
            },
        ),
    ]
