# Generated by Django 3.0.4 on 2020-03-25 16:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('review', '0007_auto_20200324_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_written', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RecentAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(auto_now_add=True)),
                ('actionDetail', models.TextField()),
                ('actionLink', models.TextField(blank=True, null=True)),
                ('actionType', models.CharField(choices=[('a', 'Alert'), ('i', 'info')], default='i', max_length=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recentActions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
