# Generated by Django 3.0.4 on 2020-03-25 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_auto_20200325_2138'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentaction',
            options={'ordering': ['dateAdded']},
        ),
    ]
