# Generated by Django 3.0.4 on 2020-03-26 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_auto_20200325_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentaction',
            options={'ordering': ['-dateAdded']},
        ),
    ]
