# Generated by Django 3.0.4 on 2020-03-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=2)),
                ('noOfReviews', models.IntegerField()),
            ],
        ),
    ]
