# Generated by Django 3.0.4 on 2020-03-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=120)),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('noOfReviews', models.IntegerField(default=0)),
                ('courseDescription', models.TextField(default='')),
                ('pageType', models.CharField(choices=[('c', 'Course'), ('P', 'Professor')], default='c', max_length=1)),
            ],
            options={
                'ordering': ['courseName'],
            },
        ),
    ]
