# Generated by Django 3.0.4 on 2020-03-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='pageType',
            field=models.CharField(choices=[('c', 'Course'), ('p', 'Professor')], default='c', max_length=1),
        ),
    ]
